castlecms/castle.cms

- HISTORY.rst
- castle/cms/browser/fourohfour.py
- castle/cms/browser/icon.py
- castle/cms/shield.py
and potential performance issue with serving static resources
> Fix 404 not being protected by login shield

- castle/cms/browser/templates/content_history.pt
Forgot to set the CSS ID correctly in the previous change
> Fixed historyview ID

- castle/cms/tiles/templates/video.pt
added aria-label to transcript /download to be more specific. removed frameborder (https://www.w3.org/TR/WCAG20-TECHS/G140) and made it a style. added title attribute to Iframe (https://www.w3.org/TR/WCAG20-TECHS/H64).
> Accessibility Fixes

- castle/cms/tiles/meta.py
added aria-label to the section tag to comply with https://www.w3.org/TR/WCAG20-TECHS/ARIA20
> added aria-label to section

- castle/cms/profiles/default/registry/controlpanel.xml
fix bug introduced in https://github.com/castlecms/castle.cms/pull/133
> register announcement data explicitly

- HISTORY.rst
- setup.py
The first thing I changed in castle...never created pull request.
> add new CastleCMS PyPi classifiers

- castle/cms/browser/audit.py
- castle/cms/browser/templates/audit-error.pt
- castle/cms/browser/templates/audit-inner.pt
- castle/cms/browser/templates/error.pt
Fix for ticket https://github.com/castlecms/castle.cms/issues/110
> Add/Revise messages regarding ES connectivity/config

- HISTORY.rst
- castle/cms/configure.zcml
- castle/cms/fragments/configure.zcml
- castle/cms/meta.zcml
- castle/cms/metaconfiguration.py
- docs/fragments.rst
- docs/index.rst
Created zcml directive so we can much more easily include new fragments into castle add-ons
> Added fragments directive

- HISTORY.rst
- castle/cms/browser/utils.py
- castle/cms/tiles/querylisting.py
- castle/cms/tiles/templates/querylisting/blog.pt
- castle/cms/tiles/templates/querylisting/compact.pt
- castle/cms/tiles/templates/querylisting/default-natural.pt
- castle/cms/tiles/templates/querylisting/default.pt
- castle/cms/tiles/templates/querylisting/grid.pt
- castle/cms/tiles/templates/querylisting/tagged.pt
...to the query listing tile default view; also fix typos in field descriptions
> add Event start and end datetimes to the query listing tile

- HISTORY.rst
- castle/cms/_scripts/export-content.py
- castle/cms/_scripts/importjson.py
- castle/cms/_scripts/importtypes.py
- castle/cms/_scripts/mjson.py
contains changes originally made in plone-5.1 branch
> improve export and import scripts

- castle/cms/browser/templates/secure-login.pt
- castle/cms/skins/castle/logged_out.cpt
- castle/cms/skins/castle/login_form.cpt
fix empty settings bug, fix expression not defined bug, fixed logged out template
> Fix several bugs relating to locking out non-backend URLs to login

- HISTORY.rst
- castle/cms/browser/search.py
- castle/cms/static/components/search.js
> add path search parameter

- HISTORY.rst
- castle/cms/browser/login.py
> remove undefined variable

- HISTORY.rst
- castle/cms/browser/content.py
- castle/cms/static/components/add-content-modal.js
- castle/cms/static/components/upload.js
- castle/cms/static/patterns/upload-update.js
- castle/cms/static/plone-logged-in.js
- castle/cms/widget_templates/file_input.pt
- castle/cms/widgets.zcml
Make chunked upload component available on edit forms with blob fields
> Chunked upload on edit forms for blob fields

- .travis.yml
- HISTORY.rst
- buildout.cfg
- castle/cms/_scripts/export-content.py
- castle/cms/_scripts/importjson.py
- castle/cms/_scripts/importtypes.py
- castle/cms/_scripts/mjson.py
- castle/cms/static/less/logged-in/control-panel.less
- castle/cms/tests/test_tiles.py
- castle/cms/tiles/querylisting.py
> Pull from master

- HISTORY.rst
- castle/cms/browser/controlpanel/settings.py
- castle/cms/browser/templates/addsite.pt
- castle/cms/browser/templates/overview.pt
- castle/cms/browser/templates/redirects-controlpanel.pt
- castle/cms/exportimport/configure.zcml
- castle/cms/exportimport/frontpagecontent.py
- castle/cms/profiles/default/actions.xml
- castle/cms/profiles/default/controlpanel.xml
- castle/cms/static/addsite/castle-addsite.js
- castle/cms/static/components/analytics-modal.js
- castle/cms/static/patterns/toolbar.js
- docs/fragments.rst
change occurrences of "Castle" to "CastleCMS"
> change "Castle" to "CastleCMS"

- HISTORY.rst
- castle/cms/fragments/templates/dashboard-welcome.pt
This caused the type to get confused and you started over essentially with "adding a type".
> fix the %20 issue that was put into the data-type.

- README.rst
- buildout.cfg
- setup.py
- travis.cfg
- versions.cfg
Previous mosaic had a bad build of css where it didn't embed images into the build css file.
> Fix mosaic build js/css

- HISTORY.rst
- castle/cms/tiles/querylisting.py
- castle/cms/toolbar.py
- setup.py
- versions.cfg
Needs https://github.com/collective/collective.elasticsearch/pull/46 merged and released before this will build
> Fix elasticsearch sorting and change default sorting of query listing

- HISTORY.rst
- castle/cms/_scripts/export-content.py
…e.g. --modifiedsince='2018-10-03 00:00:00'
> new export script args --modifiedsince and --createdsince

- HISTORY.rst
- castle/cms/_scripts/importjson.py
> import process fixes

- HISTORY.rst
- buildout.cfg
- castle/cms/cron/_upgrade_sites.py
- castle/cms/files/aws.py
- requirements.txt
- versions.cfg
> fix upgrade and TypeError

- HISTORY.rst
- setup.py
- travis.cfg
- versions.cfg
Fixes styles
from:
to:
Open to anyone improving it more!
> Upgrade mosaic to fix layout selection styles

- HISTORY.rst
- castle/cms/configure.zcml
- castle/cms/jbot.py
> Fix jbot from bleeding customizations

- HISTORY.rst
- castle/cms/browser/viewlets/socialtags.py
> use `summary_large_image` twitter card instead of `summary`

- HISTORY.rst
- castle/cms/easyform/supermodel.py
> Fix adding Query Choice easyform field

- HISTORY.rst
- castle/cms/defaults.py
- castle/cms/tiles/existing.py
- castle/cms/tiles/gallery.py
- castle/cms/tiles/image.py
- castle/cms/tiles/querylisting.py
- castle/cms/tiles/video.py
- docs/configuration.rst
- docs/index.rst
> Be able to configure some default settings with environment variables

- castle/cms/browser/content/analytics.py
Skip some work if cache is going to be used, return some useful error messages
> google analytics issue

- .travis.yml
- castle/cms/tests/test_es.py
All I needed to do was to specify for one function in the test to have the transaction manager to only commit what is in the function and not outside the function.
> 591 dw travis unit tests failure

- castle/cms/cache.py
Just added into the cache __set_item__ function allowing it to recover from a redis-server failure and if needed use a different cache altogether for the item in question.
> 500 dw redis server disconnect message

- castle/cms/browser/controlpanel/templates/mapper.pt
- castle/cms/browser/templates/atom.xml.pt
- castle/cms/tests/test_crawl.py
- castle/cms/tiles/metadata.py
Just changed the plone metadata tags to castle.cms and changed the metadata.py tile so that it outputs the currently correct version of castle.cms.
> Replaced several metadata tags from plone to castle.cms

- castle/cms/browser/content/__init__.py
- castle/cms/commands.py
Here you go, the docsplit version of the 590 fix.  I will be updating the docsplit branch using the old 590 fix because there are several fixes and improvements I want the docsplit branch to keep.
> 590 v2 dw fillable pdf using docsplit

- .gitignore
This allows for untracked local buildout configurations.
> add local.cfg to .gitignore

- castle/cms/_scripts/importtypes.py
- castle/cms/_scripts/mjson.py
This fixes a couple errors in the import script related to mime types, assumptions and default `else` logic.
> some fixes for import script

- HISTORY.rst
- castle/cms/browser/controlpanel/archival.py
- castle/cms/browser/controlpanel/templates/archives-review.pt
- castle/cms/profiles/2_6_14/metadata.xml
- castle/cms/profiles/2_6_14/registry/resources.xml
- castle/cms/profiles/default/metadata.xml
- castle/cms/profiles/default/registry/resources.xml
- castle/cms/static/components/review-archives.js
- castle/cms/upgrades.zcml
- castle/cms/upgrades/upgrade_2_6_14.py
by moving archival-review js to component and using resource registry to load
> fix js loading error

- castle/cms/browser/security/login.py
- castle/cms/browser/utils.py
- castle/cms/interfaces/utils.py
- castle/cms/skins/castle/mail_password_template.pt
- castle/cms/skins/castle/registered_notify_template.pt
Also fixes: `make sure the site logo does not show up on any login or "bad domain" view when scrub_title_logo_to_backend_login is enabled.`
> 553 When creating a user, the confirmation link sent can lead to a site URL that does not allow logins

- castle/cms/browser/security/login.py
- castle/cms/static/components/secure-login.js
- castle/cms/tests/test_login.py
trying to fix authentication issue requiring browser refresh
> reset secure flow state and retry before 403

- castle/cms/browser/controlpanel/templates/announcements.pt
- castle/cms/browser/controlpanel/templates/social.pt
- castle/cms/browser/files/files.py
- castle/cms/browser/templates/pad-view.pt
- castle/cms/linkreporter.py
- castle/cms/static/addsite/castle-addsite.js
- castle/cms/static/addsite/inputs.js
- docs/configuration.rst
mostly fixing replacing some instances of 'setup' (noun) with 'set up' (open compound verb)
> grammer fix

- castle/cms/tiles/gallery.py
Related PR in theme package: https://bteamg.wildcardcorp.com/FBI/fbigov-theme/pulls/54
> Add height property to gallery tile schema

- HISTORY.rst
- castle/cms/pdf/generator.py
- castle/cms/tasks/pdf.py
- castle/cms/utils/content.py
Allow unrestricted traverse to be selected when creating a pdf. defaults to restricted traverse.
> unrestricted traverse  option when creating a pdf

- castle/cms/files/aws.py
- castle/cms/syndication.py
- castle/cms/tests/test_files.py
display size of file if moved to s3
> check if obj exists on s3
